# Generated by Django 5.1.4 on 2025-01-07 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Empresa', '0001_initial'),
        ('Mesero', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id_periodo', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('X', 'X'), ('M', 'M'), ('D', 'D')], max_length=1)),
                ('desde', models.DateTimeField()),
                ('hasta', models.DateTimeField()),
            ],
            options={
                'db_table': 'periodo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PagosEfectivo',
            fields=[
                ('id_pagoefectivo', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('X', 'X'), ('P', 'P')], max_length=1)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=9)),
                ('cantidadentregada', models.DecimalField(db_column='cantidadentregada', decimal_places=2, max_digits=9)),
                ('cambioeentregado', models.DecimalField(db_column='cambioeentregado', decimal_places=2, max_digits=9)),
                ('hora_de_pago', models.DateTimeField()),
                ('id_cuentacobrador', models.ForeignKey(db_column='id_cuentacobrador', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, to='Mesero.pedidos')),
            ],
            options={
                'db_table': 'pagosefectivo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PagosPasarela',
            fields=[
                ('id_pagopasarela', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('E', 'E'), ('C', 'C')], max_length=1)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=9)),
                ('hora_de_pago', models.DateTimeField()),
                ('codigo_unico', models.IntegerField(null=True)),
                ('id_pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, to='Mesero.pedidos')),
            ],
            options={
                'db_table': 'pagospasarela',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PagosTransferencia',
            fields=[
                ('id_pagotransferencia', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('E', 'E'), ('C', 'C')], max_length=1)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=9)),
                ('hora_de_pago', models.DateTimeField()),
                ('comprobante', models.BinaryField()),
                ('hora_confirmacion_pago', models.DateTimeField(null=True)),
                ('id_cuentacobrador', models.ForeignKey(db_column='id_cuentacobrador', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, to='Mesero.pedidos')),
            ],
            options={
                'db_table': 'pagostransferencia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tipopago', models.CharField(choices=[('H', 'H'), ('S', 'S'), ('T', 'T'), ('M', 'M')], max_length=1)),
                ('horadepago', models.DateTimeField()),
                ('idempleado', models.ForeignKey(db_column='idempleado', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idperiodo', models.ForeignKey(db_column='idperiodo', on_delete=django.db.models.deletion.CASCADE, to='pagos.periodo')),
            ],
            options={
                'db_table': 'pagos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tipopago',
            fields=[
                ('id_tipopago', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('X', 'X'), ('M', 'M'), ('D', 'D')], max_length=1)),
                ('tipo_pago', models.CharField(choices=[('H', 'H'), ('S', 'S'), ('T', 'T'), ('M', 'M')], db_column='tipopago', max_length=1)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=8)),
                ('idempresa', models.ForeignKey(db_column='idempresa', on_delete=django.db.models.deletion.CASCADE, to='Empresa.empresa')),
            ],
            options={
                'db_table': 'tipopago',
                'managed': True,
            },
        ),
    ]
