from django.urls import path
from .views import *

urlpatterns = [
    path('obtener_usuario/<int:id_usuario>/', ObtenerMeseroView.as_view(), name='obtener_mesero'),
    path('tomar_pedido/<int:id_cuenta>/', TomarPedido.as_view(), name='tomar_pedido'),
    path('ver_factura/<int:id_pedido>/', ver_factura, name='ver_factura'),
    path('mesero/<int:id_cuenta>/mesa/<int:id_mesa>/pedidos/', pedidos_del_mesero, name='pedidos_mesero_mesa'),
    path('pedidos/', ListaPedidos.as_view(), name='pedidos'),
    path('pedidoslocal/<int:id_cuenta>/', TomarPedidoSinMesa.as_view(), name='tomar_pedido_2'),
    path('listpedidos/', ListaPedidosMesero.as_view(), name='ListaPedidosMesero'),
    path('confirmarpedido/', ConfirmarPedido.as_view(), name='ConfirmarPedido'),
    path('listar_meseros/', ListaMeseros.as_view(), name='listar_meseros'),
    path('lista_facturas/', ListaFacturas.as_view(), name='lista_facturas'),
    path('crear_reverso_factura/<int:id_factura>/', CrearReversoFactura.as_view(), name='crear_reverso_factura'),
    path('validar_facturas/', FacturasValidadasReportes.as_view(), name='validar_facturas'),
    path('listar_notas_credito/<int:id_notacredito>/', ListaNotasCredito.as_view(), name='listar_notas_credito'),
    path('detalle_factura/<int:id_factura>/', DetalleFacturaView.as_view(), name='detalle_factura'),
    path('lista_facturas_con_detalles/<int:id_factura>/', ListaFacturasConDetalles.as_view(), name='lista_facturas_con_detalles'),
    path('listapedidospagados/', ListaTodosPedidosReportes.as_view(), name='listatodospagados'),
    path('listapedidospagado/<int:id_mesero>/', ListaPedidosReportes.as_view(), name='listapagados'),
    path('listapedidossucursal/', ListaPedidosSucursalReportes.as_view(), name='listapagadossucursal'),
    path('listapedidossucursalid/<int:id_sucursal>/', ListaPedidosIdSucuReportes.as_view(), name='listapagadossucursalid'),
    path('listapedidosproducto/', ListaPedidosProductoReportes.as_view(), name='listapagadosproducto'),
    path('listapedidosproductos/<int:id_producto>/', ListaPedidosIdProductoReportes.as_view(), name='listapagadosproductoid'),
    path('listapedidostipoproducto/', ListaPedidosTipoPReportes.as_view(), name='listapagadostipo'),
    path('listapedidostipoproductos/<int:id_tipoproducto>/', ListaTipos.as_view(), name='listapagadostipoid'),
    path('factura_detalles_nota_credito/<int:id_factura>/', FacturaDetallesNotaCredito.as_view(), name='factura_detalles_nota_credito'),
    path('lista_reverso_factura/', ReversoFacturaReporte.as_view(), name='reversofactura'),
    path('factura_v_report/', FacturasConCodigoReport.as_view(), name='facturavalidas'),
    path('factura_n_report/', FacturasSinCodigoReport.as_view(), name='facturanovalida'),
    path('listapedidosmes/', ListaPedidosMes.as_view(), name='pedidosmes'),
    path('listaventasmesero/', MayorVentas.as_view(), name='top ventas meseros'),
    path('listaventassucursal/', MayorVentasSucursal.as_view(), name='top ventas sucursal'),
    path('fechatop/', FechaVentas.as_view(), name='fecha min max top ventas'),
    path('fechasucursal/<int:id_sucursal>/', FechaSucursal.as_view(), name='fecha min max sucursal'),
    path('fechamesero/<int:id_mesero>/', FechaMesero.as_view(), name='fecha min max mesero'),
    path('fechaproducto/<int:id_producto>/', FechaProducto.as_view(), name='fecha min max producto'),
    path('fechatipoproducto/<int:id_tipoproducto>/', FechaTipoProducto.as_view(), name='fecha min max tipo producto'),
    path('lista_facturas_m/<int:id_mesero>/', FacturasPorMesero.as_view(), name='lista_facturas_mesero'),
    path('lista_facturas_s/<int:id_sucursal>/', FacturasPorSucursal.as_view(), name='lista_facturas_sucursal'),
]