# Generated by Django 5.0.4 on 2024-12-20 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('imagencategoria', models.BinaryField(null=True)),
                ('catnombre', models.CharField(max_length=300)),
                ('descripcion', models.CharField(max_length=500, null=True)),
                ('sestado', models.CharField(max_length=1)),
                ('mostracliente', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'categorias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TiposProductos',
            fields=[
                ('id_tipoproducto', models.AutoField(primary_key=True, serialize=False)),
                ('tpnombre', models.CharField(max_length=300)),
                ('descripcion', models.CharField(max_length=500, null=True)),
                ('sestado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'tiposproductos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('idum', models.AutoField(primary_key=True, serialize=False)),
                ('nombreum', models.CharField(max_length=100)),
                ('sestado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'unidadmedida',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id_componente', models.AutoField(db_column='id_componente', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(null=True)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(max_length=100)),
                ('sestado', models.CharField(max_length=1)),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='Producto.categorias')),
                ('id_um', models.ForeignKey(db_column='id_um', on_delete=django.db.models.deletion.CASCADE, to='Producto.unidadmedida')),
            ],
            options={
                'db_table': 'componente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EnsambleComponente',
            fields=[
                ('id_ensamblec', models.AutoField(primary_key=True, serialize=False)),
                ('padrecantidad', models.DecimalField(decimal_places=2, max_digits=9)),
                ('id_componentepadre', models.ForeignKey(db_column='id_componentepadre', on_delete=django.db.models.deletion.CASCADE, to='Producto.componente')),
                ('id_umpadre', models.ForeignKey(db_column='id_umpadre', on_delete=django.db.models.deletion.CASCADE, to='Producto.unidadmedida')),
            ],
            options={
                'db_table': 'ensamblecomponente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('imagenp', models.BinaryField(null=True)),
                ('puntosp', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('codprincipal', models.CharField(max_length=25, null=True)),
                ('nombreproducto', models.CharField(max_length=300)),
                ('descripcionproducto', models.CharField(blank=True, max_length=300, null=True)),
                ('preciounitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('iva', models.CharField(choices=[('0', '0'), ('1', '1')], max_length=1)),
                ('ice', models.CharField(choices=[('0', '0'), ('1', '1')], max_length=1)),
                ('irbpnr', models.CharField(choices=[('0', '0'), ('1', '1')], max_length=1)),
                ('sestado', models.CharField(max_length=1)),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='Producto.categorias')),
                ('id_um', models.ForeignKey(db_column='id_um', on_delete=django.db.models.deletion.CASCADE, to='Producto.unidadmedida')),
            ],
            options={
                'db_table': 'producto',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='categorias',
            name='id_tipoproducto',
            field=models.ForeignKey(db_column='id_tipoproducto', on_delete=django.db.models.deletion.CASCADE, to='Producto.tiposproductos'),
        ),
        migrations.CreateModel(
            name='EnsambleUnidadMedida',
            fields=[
                ('ideum', models.AutoField(primary_key=True, serialize=False)),
                ('cantidadconversion', models.DecimalField(decimal_places=6, max_digits=12)),
                ('idumc', models.ForeignKey(db_column='idumc', on_delete=django.db.models.deletion.CASCADE, related_name='ensambles_idumc', to='Producto.unidadmedida')),
                ('idump', models.ForeignKey(db_column='idump', on_delete=django.db.models.deletion.CASCADE, related_name='ensambles_idump', to='Producto.unidadmedida')),
            ],
            options={
                'db_table': 'ensambleunidadmedida',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EnsambleProducto',
            fields=[
                ('id_emsamblep', models.AutoField(primary_key=True, serialize=False)),
                ('padrecantidad', models.DecimalField(decimal_places=2, max_digits=9)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='Producto.producto')),
                ('id_um', models.ForeignKey(db_column='id_um', on_delete=django.db.models.deletion.CASCADE, to='Producto.unidadmedida')),
            ],
            options={
                'db_table': 'ensambleproducto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetalleEnsambleProducto',
            fields=[
                ('id_detalleensamblep', models.AutoField(primary_key=True, serialize=False)),
                ('cantidadhijo', models.DecimalField(decimal_places=2, max_digits=9)),
                ('id_componentehijo', models.ForeignKey(db_column='id_componentehijo', on_delete=django.db.models.deletion.CASCADE, to='Producto.componente')),
                ('id_emsamblep', models.ForeignKey(db_column='id_emsamblep', on_delete=django.db.models.deletion.CASCADE, to='Producto.ensambleproducto')),
                ('id_umhijo', models.ForeignKey(db_column='id_umhijo', on_delete=django.db.models.deletion.CASCADE, to='Producto.unidadmedida')),
            ],
            options={
                'db_table': 'detalleensambleproducto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetalleEnsambleComponente',
            fields=[
                ('id_detalleensamblec', models.AutoField(primary_key=True, serialize=False)),
                ('cantidadhijo', models.DecimalField(decimal_places=2, max_digits=9)),
                ('id_componentehijo', models.ForeignKey(db_column='id_componentehijo', on_delete=django.db.models.deletion.CASCADE, to='Producto.componente')),
                ('id_ensamblec', models.ForeignKey(db_column='id_ensamblec', on_delete=django.db.models.deletion.CASCADE, to='Producto.ensamblecomponente')),
                ('id_umhijo', models.ForeignKey(db_column='id_umhijo', on_delete=django.db.models.deletion.CASCADE, to='Producto.unidadmedida')),
            ],
            options={
                'db_table': 'detalleensamblecomponente',
                'managed': True,
            },
        ),
    ]
