# Generated by Django 5.1.4 on 2025-01-16 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0002_categoriascombos_combo_detallecombo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impuestos',
            fields=[
                ('id_impuesto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Impuesto',
                'verbose_name_plural': 'Impuestos',
                'db_table': 'impuestos',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': True, 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.RemoveField(
            model_name='producto',
            name='ice',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='irbpnr',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='iva',
        ),
        migrations.CreateModel(
            name='ProductoImpuestos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_impuesto', models.ForeignKey(db_column='id_impuesto', on_delete=django.db.models.deletion.CASCADE, to='Producto.impuestos')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='Producto.producto')),
            ],
            options={
                'verbose_name': 'Relación Producto-Impuesto',
                'verbose_name_plural': 'Relaciones Producto-Impuestos',
                'db_table': 'producto_impuestos',
                'managed': True,
                'unique_together': {('id_producto', 'id_impuesto')},
            },
        ),
    ]
