# Generated by Django 5.0.4 on 2024-12-20 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('enombre', models.CharField(default='Nombre de Empresa', max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('etelefono', models.CharField(blank=True, max_length=10, null=True)),
                ('correoelectronico', models.CharField(blank=True, max_length=256, null=True)),
                ('fechafundacion', models.DateField()),
                ('sitioweb', models.CharField(blank=True, max_length=2000, null=True)),
                ('eslogan', models.CharField(blank=True, max_length=300, null=True)),
                ('elogo', models.BinaryField(blank=True, null=True)),
                ('edescripcion', models.CharField(blank=True, max_length=800, null=True)),
                ('docmenu', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'empresa',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Horariossemanales',
            fields=[
                ('id_horarios', models.AutoField(primary_key=True, serialize=False)),
                ('hordescripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('tipohorario', models.CharField(max_length=1)),
                ('nombreh', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'horariossemanales',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id_sucursal', models.AutoField(primary_key=True, serialize=False)),
                ('srazon_social', models.CharField(max_length=300)),
                ('sruc', models.CharField(max_length=20)),
                ('sestado', models.CharField(max_length=1)),
                ('scapacidad', models.CharField(blank=True, max_length=1, null=True)),
                ('scorreo', models.CharField(max_length=300)),
                ('stelefono', models.CharField(blank=True, max_length=300, null=True)),
                ('sdireccion', models.CharField(max_length=300)),
                ('snombre', models.CharField(blank=True, max_length=300, null=True)),
                ('fsapertura', models.DateTimeField(auto_now_add=True)),
                ('firmaelectronica', models.BinaryField(blank=True, null=True)),
                ('imagensucursal', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sucursales',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetalleHorariosSemanales',
            fields=[
                ('id_dethorarios', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.CharField(choices=[('L', 'Lunes'), ('M', 'Martes'), ('X', 'Miércoles'), ('J', 'Jueves'), ('V', 'Viernes'), ('S', 'Sábado'), ('D', 'Domingo')], max_length=1)),
                ('horainicio', models.TimeField()),
                ('horafin', models.TimeField()),
                ('id_horarios', models.ForeignKey(db_column='id_horarios', on_delete=django.db.models.deletion.CASCADE, to='Empresa.horariossemanales')),
            ],
            options={
                'db_table': 'detallehorariossemanales',
                'managed': True,
            },
        ),
    ]
