# Generated by Django 5.0.4 on 2024-12-20 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Empresa', '0001_initial'),
        ('Ubicaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursales',
            name='id_cuenta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sucursales_cuenta', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sucursales',
            name='id_empresa',
            field=models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.DO_NOTHING, related_name='sucursales_empresa', to='Empresa.empresa'),
        ),
        migrations.AddField(
            model_name='sucursales',
            name='id_geosector',
            field=models.ForeignKey(blank=True, db_column='id_geosector', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sucursales_geosector', to='Ubicaciones.geosectores'),
        ),
        migrations.AddField(
            model_name='sucursales',
            name='id_horarios',
            field=models.ForeignKey(db_column='id_horarios', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sucursales_horarios', to='Empresa.horariossemanales'),
        ),
        migrations.AddField(
            model_name='sucursales',
            name='id_ubicacion',
            field=models.ForeignKey(blank=True, db_column='id_ubicacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sucursales_ubicacion', to='Ubicaciones.ubicaciones'),
        ),
    ]
