# Generated by Django 5.1.4 on 2025-01-07 02:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Bodega', '0002_initial'),
        ('Producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleMovimientoInventario',
            fields=[
                ('id_detallemovimiento', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=9)),
                ('tipo', models.CharField(choices=[('E', 'Entrada'), ('S', 'Salida')], max_length=1)),
                ('id_articulo', models.ForeignKey(blank=True, db_column='id_articulo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Producto.componente')),
                ('id_producto', models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Producto.producto')),
            ],
            options={
                'db_table': 'detallemovimientoinventario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('stock_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('cantidad_disponible', models.DecimalField(decimal_places=2, max_digits=9)),
                ('id_bodega', models.ForeignKey(db_column='id_bodega', on_delete=django.db.models.deletion.DO_NOTHING, to='Bodega.bodegas')),
                ('id_componente', models.ForeignKey(blank=True, db_column='id_componente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Producto.componente')),
                ('id_producto', models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Producto.producto')),
                ('id_um', models.ForeignKey(blank=True, db_column='id_um', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Producto.unidadmedida')),
            ],
            options={
                'db_table': 'inventario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id_movimientoinventario', models.AutoField(primary_key=True, serialize=False)),
                ('fechahora', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipomovimiento', models.CharField(choices=[('E', 'Entrada'), ('S', 'Salida'), ('P', 'Preparacion'), ('R', 'Reversion')], max_length=1)),
                ('observacion', models.CharField(max_length=500)),
                ('sestado', models.CharField(choices=[('0', '0'), ('1', '1')], max_length=1)),
                ('id_bodega', models.ForeignKey(blank=True, db_column='id_bodega', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Bodega.bodegas')),
            ],
            options={
                'db_table': 'movimientoinventario',
                'managed': True,
            },
        ),
    ]
