# Generated by Django 5.0.4 on 2024-12-20 18:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleMovimientoInventario',
            fields=[
                ('id_detallemovimiento', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=9)),
                ('tipo', models.CharField(choices=[('E', 'Entrada'), ('S', 'Salida')], max_length=1)),
            ],
            options={
                'db_table': 'detallemovimientoinventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('stock_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('cantidad_disponible', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                'db_table': 'inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id_movimientoinventario', models.AutoField(primary_key=True, serialize=False)),
                ('fechahora', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipomovimiento', models.CharField(choices=[('E', 'Entrada'), ('S', 'Salida'), ('P', 'Preparacion'), ('R', 'Reversion')], max_length=1)),
                ('observacion', models.CharField(max_length=500)),
                ('sestado', models.CharField(choices=[('0', '0'), ('1', '1')], max_length=1)),
            ],
            options={
                'db_table': 'movimientoinventario',
                'managed': False,
            },
        ),
    ]
