# Generated by Django 5.1.4 on 2025-01-07 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventario', '0001_initial'),
        ('Mesero', '0001_initial'),
        ('Proveedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='id_cuenta',
            field=models.ForeignKey(db_column='id_cuenta', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='id_pedido',
            field=models.ForeignKey(blank=True, db_column='id_pedido', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Mesero.pedidos'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='id_pedidoproveedor',
            field=models.ForeignKey(blank=True, db_column='id_pedidoproveedor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Proveedores.pedidosproveedor'),
        ),
        migrations.AddField(
            model_name='detallemovimientoinventario',
            name='id_movimientoinventario',
            field=models.ForeignKey(db_column='id_movimientoinventario', on_delete=django.db.models.deletion.DO_NOTHING, to='Inventario.movimientoinventario'),
        ),
    ]
