# Generated by Django 5.0.4 on 2024-12-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codigoautorizacion',
            fields=[
                ('id_codigosauto', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_autorizacion', models.CharField(blank=True, max_length=49, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('fecha_autorizacion', models.DateField(blank=True, null=True)),
                ('ruc', models.CharField(blank=True, max_length=13, null=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'codigoautorizacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Codigosri',
            fields=[
                ('id_codigosri', models.AutoField(primary_key=True, serialize=False)),
                ('numero_factura_desde', models.CharField(max_length=9)),
                ('numero_factura_hasta', models.CharField(max_length=9)),
                ('rango_desde', models.CharField(max_length=9)),
                ('rango_hasta', models.CharField(max_length=9)),
            ],
            options={
                'db_table': 'codigosri',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Puntofacturacion',
            fields=[
                ('id_puntofacturacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombrepunto', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=3)),
                ('sestado', models.CharField(max_length=1)),
                ('ruc', models.CharField(blank=True, max_length=13, null=True)),
            ],
            options={
                'db_table': 'puntofacturacion',
                'managed': False,
            },
        ),
    ]
