# Generated by Django 5.1.4 on 2025-01-07 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CodigoFactura', '0001_initial'),
        ('Mesero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntofacturacion',
            name='id_mesero',
            field=models.ForeignKey(blank=True, db_column='id_mesero', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Mesero.meseros'),
        ),
        migrations.AlterUniqueTogether(
            name='codigosri',
            unique_together={('rango_desde', 'rango_hasta')},
        ),
    ]
