# Generated by Django 5.1.4 on 2025-01-07 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Bodega', '0001_initial'),
        ('Empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodegas',
            name='id_sucursal',
            field=models.ForeignKey(db_column='id_sucursal', on_delete=django.db.models.deletion.CASCADE, to='Empresa.sucursales'),
        ),
    ]
