# Generated by Django 5.0.4 on 2024-12-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detallepedidoproveedor',
            fields=[
                ('id_detallepedidoproveedor', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=9)),
                ('costounitario', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                'db_table': 'detallepedidoproveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedidosproveedor',
            fields=[
                ('id_pedidoproveedor', models.AutoField(primary_key=True, serialize=False)),
                ('fechapedido', models.DateTimeField()),
                ('fechaentregaesperada', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(max_length=1)),
                ('observacion', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'pedidosproveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.AutoField(db_column='id_proveedor', primary_key=True, serialize=False)),
                ('nombreproveedor', models.CharField(db_column='nombreproveedor', max_length=300)),
                ('direccionproveedor', models.CharField(blank=True, db_column='direccionproveedor', max_length=300, null=True)),
                ('telefonoproveedor', models.CharField(blank=True, db_column='telefonoproveedor', max_length=10, null=True)),
                ('correoproveedor', models.CharField(blank=True, db_column='correoproveedor', max_length=256, null=True)),
                ('sestado', models.CharField(choices=[('0', '0'), ('1', '1')], db_column='sestado', max_length=1)),
            ],
            options={
                'db_table': 'proveedores',
                'managed': False,
            },
        ),
    ]
