# Generated by Django 5.1.4 on 2025-01-07 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Administrador', '0001_initial'),
        ('Bodega', '0001_initial'),
        ('Producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidosproveedor',
            fields=[
                ('id_pedidoproveedor', models.AutoField(primary_key=True, serialize=False)),
                ('fechapedido', models.DateTimeField()),
                ('fechaentregaesperada', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(max_length=1)),
                ('observacion', models.CharField(blank=True, max_length=500, null=True)),
                ('id_bodega', models.ForeignKey(db_column='id_bodega', on_delete=django.db.models.deletion.DO_NOTHING, to='Bodega.bodegas')),
            ],
            options={
                'db_table': 'pedidosproveedor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Detallepedidoproveedor',
            fields=[
                ('id_detallepedidoproveedor', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=9)),
                ('costounitario', models.DecimalField(decimal_places=2, max_digits=9)),
                ('id_componente', models.ForeignKey(blank=True, db_column='id_componente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Producto.componente')),
                ('id_producto', models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Producto.producto')),
                ('id_um', models.ForeignKey(blank=True, db_column='id_um', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Producto.unidadmedida')),
                ('id_pedidoproveedor', models.ForeignKey(db_column='id_pedidoproveedor', on_delete=django.db.models.deletion.DO_NOTHING, to='Proveedores.pedidosproveedor')),
            ],
            options={
                'db_table': 'detallepedidoproveedor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.AutoField(db_column='id_proveedor', primary_key=True, serialize=False)),
                ('nombreproveedor', models.CharField(db_column='nombreproveedor', max_length=300)),
                ('direccionproveedor', models.CharField(blank=True, db_column='direccionproveedor', max_length=300, null=True)),
                ('telefonoproveedor', models.CharField(blank=True, db_column='telefonoproveedor', max_length=10, null=True)),
                ('correoproveedor', models.CharField(blank=True, db_column='correoproveedor', max_length=256, null=True)),
                ('sestado', models.CharField(choices=[('0', '0'), ('1', '1')], db_column='sestado', max_length=1)),
                ('id_administrador', models.ForeignKey(db_column='id_administrador', on_delete=django.db.models.deletion.DO_NOTHING, to='Administrador.administrador')),
            ],
            options={
                'db_table': 'proveedores',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='pedidosproveedor',
            name='id_proveedor',
            field=models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.DO_NOTHING, to='Proveedores.proveedores'),
        ),
    ]
