# Generated by Django 5.1.4 on 2025-01-07 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geosectores',
            fields=[
                ('id_geosector', models.AutoField(primary_key=True, serialize=False)),
                ('fechacreaciong', models.DateTimeField()),
                ('secnombre', models.CharField(max_length=300)),
                ('secdescripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('sectipo', models.CharField(max_length=1)),
                ('secestado', models.CharField(max_length=1)),
                ('sestado', models.CharField(max_length=1)),
                ('tarifa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'geosectores',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ubicaciones',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('udescripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('sestado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'ubicaciones',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetalleGeosector',
            fields=[
                ('id_detallegeosector', models.AutoField(primary_key=True, serialize=False)),
                ('id_geosector', models.ForeignKey(db_column='id_geosector', on_delete=django.db.models.deletion.CASCADE, to='Ubicaciones.geosectores')),
                ('id_ubicacion', models.ForeignKey(db_column='id_ubicacion', on_delete=django.db.models.deletion.CASCADE, related_name='Geosector_ubicacion', to='Ubicaciones.ubicaciones')),
            ],
            options={
                'db_table': 'detalle_geosector',
                'managed': True,
            },
        ),
    ]
