# Generated by Django 5.1.4 on 2025-01-07 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_administrador', models.AutoField(primary_key=True, serialize=False)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('apellido', models.CharField(max_length=300)),
                ('nombre', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'administrador',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='datosBancarios',
            fields=[
                ('id_cuenta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_banco', models.CharField(max_length=100)),
                ('tipo_cuenta', models.CharField(max_length=50)),
                ('num_cuenta', models.CharField(max_length=100)),
                ('nombreapellidos', models.CharField(max_length=100)),
                ('identificacion', models.CharField(max_length=100)),
                ('correoelectronico', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'datos_bancarios',
                'managed': True,
            },
        ),
    ]
