# Generated by Django 5.0.4 on 2024-12-21 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Combos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combo',
            name='id_catcombo',
        ),
        migrations.RemoveField(
            model_name='detallecombo',
            name='id_combo',
        ),
        migrations.RemoveField(
            model_name='detallecombo',
            name='id_producto',
        ),
        migrations.DeleteModel(
            name='CategoriasCombos',
        ),
        migrations.DeleteModel(
            name='Combo',
        ),
        migrations.DeleteModel(
            name='DetalleCombo',
        ),
    ]
