# Generated by Django 5.0.4 on 2024-12-20 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisosPrincipales',
            fields=[
                ('id_aviso', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('imagen', models.BinaryField(blank=True, null=True)),
                ('sestado', models.CharField(max_length=1)),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.CASCADE, to='Empresa.empresa')),
            ],
            options={
                'db_table': 'avisosprincipales',
                'managed': True,
            },
        ),
    ]
