# Generated by Django 5.0.4 on 2024-12-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReversionMovimientoInventario',
            fields=[
                ('id_reversion', models.AutoField(primary_key=True, serialize=False)),
                ('fechahora', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'reversionmovimientoinventario',
                'managed': False,
            },
        ),
    ]
