# Generated by Django 5.1.4 on 2025-01-07 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReversionMovimientoInventario',
            fields=[
                ('id_reversion', models.AutoField(primary_key=True, serialize=False)),
                ('fechahora', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(max_length=255)),
                ('id_cuenta', models.ForeignKey(db_column='id_Cuenta', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_movimientoinventario', models.ForeignKey(db_column='id_MovimientoInventario', on_delete=django.db.models.deletion.CASCADE, to='Inventario.movimientoinventario')),
            ],
            options={
                'db_table': 'reversionmovimientoinventario',
                'managed': True,
            },
        ),
    ]
