# Generated by Django 5.1.4 on 2025-01-07 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecompensasCombos',
            fields=[
                ('id_recompensacombo', models.AutoField(primary_key=True, serialize=False)),
                ('puntos_recompensa_combo', models.DecimalField(decimal_places=0, max_digits=3)),
                ('sestado', models.CharField(choices=[('0', '0'), ('1', '1')], max_length=1)),
            ],
            options={
                'db_table': 'recompensascombos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RecompensasProductos',
            fields=[
                ('id_recompensaproducto', models.AutoField(primary_key=True, serialize=False)),
                ('puntos_recompensa_producto', models.DecimalField(decimal_places=0, max_digits=3)),
                ('sestado', models.CharField(choices=[('0', '0'), ('1', '1')], max_length=1)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='Producto.producto')),
            ],
            options={
                'db_table': 'recompensasproductos',
                'managed': True,
            },
        ),
    ]
