# Generated by Django 5.0.4 on 2024-12-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecompensasCombos',
            fields=[
                ('id_recompensacombo', models.AutoField(primary_key=True, serialize=False)),
                ('puntos_recompensa_combo', models.DecimalField(decimal_places=0, max_digits=3)),
                ('sestado', models.CharField(choices=[('0', '0'), ('1', '1')], max_length=1)),
            ],
            options={
                'db_table': 'recompensascombos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecompensasProductos',
            fields=[
                ('id_recompensaproducto', models.AutoField(primary_key=True, serialize=False)),
                ('puntos_recompensa_producto', models.DecimalField(decimal_places=0, max_digits=3)),
                ('sestado', models.CharField(choices=[('0', '0'), ('1', '1')], max_length=1)),
            ],
            options={
                'db_table': 'recompensasproductos',
                'managed': False,
            },
        ),
    ]
